services:

  mysql:
    image: mysql:8.0
    container_name: workflowx-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Dhiraj@123
      MYSQL_DATABASE: workflowx
    ports:
      - "3307:3306"

  backend:
    image: workflowx-backend:latest
    container_name: workflowx-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    image: workflowx-frontend:latest
    container_name: workflowx-frontend
    ports:
      - "5173:5173"